import { std } from "wow/wotlk";

std.Items.create('mod','id')
    .Name.enGB.set('Custom Cape')
    .Bonding.BINDS_ON_PICKUP.set()
    .Class.CLOTH_EQUIP.set()
    .InventoryType.BACK.set()
    .Material.CLOTH.set()
    .Armor.set(169)
    .Disenchant.set(68)
    .ItemLevel.set(251)
    .MaxStack.set(1)
    .SocketBonus.set(2865)
    .SoundOverride.set(-1)
    .Socket.add('RED',0)
    .Stats.add('SPELL_POWER',85)
    .Stats.add('STAMINA',61)
    .Stats.add('INTELLECT',61)
    .Stats.add('HASTE_RATING',45)
    .Stats.add('MANA_REGENERATION',27)
    .DisplayInfo.modRefCopy('mod','id_display',x=>x
        .Icon.set('inv_misc_cape_20')
        .Models.set(0,'','cape_plate_sunwell_d_01turquoise')
        .GeosetGroup.setIndex(0,1)
    )